# 🚫 STOP — THIS IS A SPECFORGE TEMPLATE

This file is a **TEMPLATE**, not an artefact.

**LLM and engineer rules:**
- Do NOT edit this file.
- Do NOT fill in this file.
- Do NOT update this file.
- Do NOT continue this file.
- Do NOT “start work” in this file.
- Do NOT generate content inside this file.
- Do NOT overwrite this file.

When asked to use this template:
1. READ ONLY.
2. Create a **NEW** file in the correct folder.
3. Populate the **NEW** file.
4. Leave this template unchanged forever.

## Strict Sequencing Rule
- **DO NOT create implementation files until the complete SpecForge chain is defined.**
- The chain MUST be completed in this exact order:
  1. Context (01-*.md)
  2. Requirement (REQ-*.md) 
  3. Feature (FEATURE-*.md)
  4. Scenario (SCENARIO-*.md)
  5. Test (TEST-*.md)
  6. Plan (PLAN-*.md)
  7. Tasks (TASK-*.md)
- Implementation code is created ONLY AFTER all 7 SpecForge artifacts exist.
- Any deviation from this sequence violates the template.

---



@{{REQ_ID_1}} @{{REQ_ID_2}}
Feature: {{FEATURE_NAME}}

---

## 🔗 SpecForge Chain Position
**This is artefact 4 of 7.**

## 🔗 SpecForge Chain
Context → Requirements (1..N) → Feature → **Scenario** → Test → Plan → Tasks  
                                      ↑ You are here

---

**REQUIREMENT TAG RULE: Feature tags MUST exactly match the requirement IDs listed in Covered Requirements below (in the same order).**

Scenario: {{SCENARIO_ID}} — [SCENARIO NAME: Copy or derive from requirement text. Do NOT invent. If requirement is action-driven, name scenario as "User/System does [action]"]

**CONSTRAINT: The Given/When/Then steps MUST be derived directly from the requirement text.  
Do NOT add detail, steps, or behaviors beyond what the requirement specifies.**

**Abbreviation rule: NEVER abbreviate requirement text. ONLY copy preconditions and outcomes verbatim from the requirement.  
If a precondition exceeds 1 line, copy it completely as written. Do NOT omit or shorten any part.**

  Given [precondition copied verbatim from the requirement — copy all of it, do not abbreviate]
  When [trigger copied verbatim from the requirement — copy exactly as written]
  Then [expected outcome copied verbatim from the requirement — copy exactly as written]

---

## Covered Requirements
This scenario validates the following requirement(s) through its Given/When/Then steps.  
**These IDs MUST match the @tags in the Feature line above (in the same order).**

- {{REQ_ID_1}}
- {{REQ_ID_2}}

---

## Domain Context
This scenario demonstrates:
- **Domain events that MUST be emitted**: [List event names from Context that this scenario triggers: e.g., "OrderConfirmed, OrderShipped"]
- **Invariants that MUST remain satisfied**: [List invariant names from Context that must still hold true after scenario executes: e.g., "Order.Total Invariant, Shipping.TrackingNumber Invariant"]

---

## SpecForge Rules
- Must reference ≥1 requirement via tags and Covered Requirements.
- Feature tags MUST exactly match Covered Requirements IDs (in same order).
- Must NOT introduce new invariants, events, or domain concepts not in the Context.
- Must demonstrate that domain events are emitted and invariants are preserved.
- All Given/When/Then text MUST be copied verbatim from the requirement — never paraphrase or abbreviate.

---

## Next Step Directive
Create a test file named `SCENARIO-{{SCENARIO_ID}}-TEST-001.md` under the relative path `../../tests/{{FEATURE_NAME}}/`.

The test MUST reference all requirement IDs covered by this scenario.

**Validation before proceeding**:
- Verify `/tests/{{FEATURE_NAME}}/` directory exists
- Verify all {{REQ_ID_X}} requirement files exist
- Verify Feature spec file exists at `../spec.md`
